FROM dunglas/frankenphp:1-php8.4-bookworm

RUN install-php-extensions pdo_mysql

RUN cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" \
    && printf "\nupload_max_filesize=6M\npost_max_size=7M\nsession.cookie_httponly=1\nsession.cookie_samesite=Lax\n" >> "$PHP_INI_DIR/php.ini"

ENV SERVER_NAME=:80
ENV APP_ENV=production

WORKDIR /app/public
COPY . /app/public
