FROM php:8.3-apache

RUN docker-php-ext-install pdo_mysql

RUN a2enmod rewrite

RUN cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" \
    && printf "\nupload_max_filesize=6M\npost_max_size=7M\nsession.cookie_httponly=1\nsession.cookie_samesite=Lax\n" >> "$PHP_INI_DIR/php.ini"

WORKDIR /var/www/html

COPY . /var/www/html/

RUN chown -R www-data:www-data /var/www/html

ENV APP_ENV=production

EXPOSE 80
